# Generated by Django 3.0 on 2020-05-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_progress', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=150, verbose_name='subject')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(default='', null=True, upload_to='videos/', verbose_name='video')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='education.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readings', models.FileField(null=True, upload_to='PDF/', verbose_name='content')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='education.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Live_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='topic_name', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class', to='education.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams', models.CharField(default='', max_length=150, null=True, verbose_name='exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_progress', models.IntegerField(null=True)),
                ('assignment_deadline', models.DateTimeField()),
                ('assignment_status', models.CharField(choices=[('1', 'Done'), ('2', 'Not Done')], default=('2', 'Not Done'), max_length=20, verbose_name='Mark as')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_video', to='education.Assignments')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_reading', models.FileField(blank=True, null=True, upload_to='PDF/', verbose_name='reading_material')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_reading', to='education.Assignments')),
            ],
        ),
    ]
