# Generated by Django 3.0 on 2020-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readings',
            name='reading_info',
            field=models.CharField(default='', max_length=500, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_info',
            field=models.CharField(default=False, max_length=500, verbose_name='Info'),
        ),
    ]
