# Generated by Django 3.0 on 2020-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_course_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='exams',
            field=models.CharField(max_length=150, verbose_name='exam'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjects',
            field=models.CharField(max_length=150, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
