# Generated by Django 3.0 on 2020-06-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_commonexamanswers_commonexamquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonexamanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commonexamanswers', to='education.CommonExamQuestions'),
        ),
    ]
