# Generated by Django 3.0 on 2020-06-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20200602_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonexamanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='education.CommonExamQuestions'),
        ),
    ]
