# Generated by Django 3.0 on 2020-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20200602_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_info',
            field=models.CharField(default='It is the medium in which objects and subjects actually come into existence, and is the medium in which their virtuality resides.This book is an introduction to logic, as contemporary logicians now understand the subject.', max_length=1000),
        ),
    ]
