# Generated by Django 3.0 on 2020-05-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20200521_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_video', models.FileField(null=True, upload_to='videos/', verbose_name='video')),
                ('assignment_content', models.CharField(max_length=150, verbose_name='subject')),
                ('assignment_progress', models.IntegerField(null=True)),
                ('assignment_deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.Course')),
            ],
        ),
    ]
