# Generated by Django 3.0 on 2020-05-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_content',
            field=models.FileField(null=True, upload_to='PDF/', verbose_name='reading_material'),
        ),
    ]
