# Generated by Django 3.0 on 2020-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20200604_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exams',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='exam'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjects',
            field=models.CharField(max_length=1000, verbose_name='subject'),
        ),
    ]
