# Generated by Django 3.0 on 2020-05-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20200524_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment_status',
            field=models.CharField(choices=[('1', 'Done'), ('2', 'Not Done')], default=('2', 'Not Done'), max_length=20, verbose_name='Mark as'),
        ),
    ]
