# Generated by Django 3.0 on 2020-05-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20200524_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_content',
            name='assignment_reading',
            field=models.FileField(blank=True, null=True, upload_to='PDF/', verbose_name='reading_material'),
        ),
        migrations.AlterField(
            model_name='assignment_content',
            name='assignment_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
