# Generated by Django 3.0 on 2020-05-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20200524_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_content',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_content', to='education.Assignments'),
        ),
    ]
