# Generated by Django 3.0 on 2020-05-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20200524_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_video', models.CharField(blank=True, max_length=40, null=True, verbose_name='vide')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='education.Assignments')),
            ],
        ),
    ]
