# Generated by Django 3.0 on 2020-05-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_reading', models.FileField(blank=True, null=True, upload_to='PDF/', verbose_name='reading_material')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_reading', to='education.Assignments')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_video', to='education.Assignments')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='Assignment_Content',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
