# Generated by Django 3.0 on 2020-05-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_auto_20200524_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='topic_name', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class', to='education.Course')),
            ],
        ),
    ]
